#! /bin/bash

rosservice call /gazebo/set_model_state "model_state:
  model_name: 'porszilo'
  pose:
    position:
      x: 3.0
      y: 1.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: 'world'"

rosservice call /rtabmap/reset
