global_costmap:

  always_send_full_costmap: true
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: static,                     type: "costmap_2d::StaticLayer"}
    - {name: inflation_global,           type: "costmap_2d::InflationLayer"}
  update_frequency: 3
  publish_frequency: 1
  transform_tolerance: 0.25 # 0.25 seconds of latency, if greater than this, planner will stop
  static_map: false
  rolling_window: false
  width: 400
  height: 400
  origin_x: 0 # -100
  origin_y: 0 # -100
  resolution: 0.05
  inflation_radius: 0.2
  publish_cost_grid: true
