odom_frame:               odom
map_frame:                map
base_frame:               base_footprint
transform_publish_period: 0
map_update_interval:      1
maxRange:                 30
maxUrange:                25
sigma:                    0.05
kernelSize:               1
lstep:                    0.05
astep:                    0.05
iterations:               5
lsigma:                   0.075
ogain:                    3.0
lskip:                    0
srr:                      0.1
srt:                      0.2
str:                      0.1
stt:                      0.2
linearUpdate:             0.1
angularUpdate:            0.1
temporalUpdate:           -1.0
resampleThreshold:        0.5
minimumScore:             300 
particles:                80
xmin:                     -50.0
ymin:                     -50.0
xmax:                     50.0
ymax:                     50.0
delta:                    0.05
llsamplerange:            0.01
llsamplestep:             0.01
lasamplerange:            0.005
lasamplestep:             0.005
