local_costmap:
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25 # 0.25 seconds of latency, if greater than this, planner will stop
  static_map: false
  rolling_window: true # Follow robot while navigating
  width: 12
  height: 12
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.05
  inflation_radius: 0.2
  publish_cost_grid: true
