subscribe_depth: true
subscribe_scan: true
subscribe_scan_cloud: true
subscribe_stereo: false
subscribe_rgbd: true
frame_id: base_footprint
map_frame_id: map
odom_frame_id: odom
queue_size: 20
publish_tf: false
tf_delay: 0.05
tf_prefix: 
wait_for_transform: true
wait_for_transform_duration: 0.1
approx_sync: true
rgbd_cameras: 1
use_action_for_goal: false
map_filter_radius: 0.5
map_filter_angle: 30.0
map_cleanup: true
latch: true
cloud_decimation: 4
cloud_max_depth: 4
cloud_voxel_size: 0.05
# cloud_floor_culling_height
# cloud_output_voxelized
# cloud_frustum_culling
# cloud_noise_filtering_radius
# cloud_noise_filtering_min_neighbors
# scan_voxel_size
# scan_output_voxelized
grid_cell_size: 0.05
grid_size: 200
# grid_eroded
# grid_unknown_space_filled
# proj_max_ground_angle
# proj_min_cluster_size
# proj_max_height
